Repository cortezaproject/corteza, pull requests merged in 2022-12, with the labels that each got.

#636 Fix paste bug for all kinds of input
  client/web/compose/src/views/Admin/Pages/Builder.vue
Labels: frontend

#671 Show loading spinner before displaying the page tree content
  client/web/compose/src/views/Admin/Pages/List.vue
  locale/en/corteza-webapp-compose/page.yaml
Labels: bug, frontend

#706 Disable dragging when filtering in CItemPicker
  lib/vue/src/components/itemPicker/CItemPicker.vue
  lib/vue/src/components/itemPicker/CItemPickerItem.vue
Labels: bug, frontend

#708 Add spinner to template editor submit button
  client/web/admin/src/views/System/Template/Editor.vue
Labels: bug, frontend, trivial

#712 Add spinner when loading actionlog in admin
  client/web/admin/src/views/System/Actionlog/Index.vue
  locale/en/corteza-webapp-admin/system.actionlog.yaml
Labels: bug, good first issue, frontend
