Repository cortezaproject/corteza, pull requests merged in 2023-05, with the labels that each got.

#1214 Fix multiline comments displaying as inline comments under privacy re…
  client/web/privacy/src/components/Requests/Comments.vue
Labels: bug, frontend

#1194 Replace admin user/role picker with vue-select
  client/web/admin/src/components/CRolePicker.vue
  client/web/admin/src/components/Role/CRoleEditorMembers.vue
  client/web/compose/src/components/ModuleFields/Editor/User.vue
  locale/en/corteza-webapp-admin/admin.yaml
Labels: enhancement, frontend

#1211 Add CInputColorPicker
  client/web/admin/src/components/User/CUserEditorAvatar.vue
  client/web/compose/src/components/ModuleFields/Configurator/File.vue
  client/web/compose/src/components/PageBlocks/CalendarBase.vue
  client/web/compose/src/components/PageBlocks/CalendarConfigurator/FeedSource/configs/Record.vue
  client/web/compose/src/components/PageBlocks/CalendarConfigurator/FeedSource/configs/Reminder.vue
  client/web/compose/src/components/PageBlocks/FileConfigurator.vue
  client/web/compose/src/components/PageBlocks/GeometryConfigurator/FeedSource/configs/Record.vue
  client/web/compose/src/components/PageBlocks/MetricConfigurator/MStyle.vue
  client/web/compose/src/components/PageBlocks/MetricConfigurator/index.vue
  client/web/compose/src/components/PageBlocks/Navigation/Configurator.vue
  client/web/reporter/src/components/Report/Blocks/DisplayElements/Configurators/Metric.vue
  lib/vue/package.json
  lib/vue/src/components/index.ts
  lib/vue/src/components/input/CInputColorPicker.vue
  lib/vue/src/components/input/index.ts
  lib/vue/yarn.lock
  locale/en/corteza-webapp-admin/general.yaml
  locale/en/corteza-webapp-admin/system.users.yaml
  locale/en/corteza-webapp-compose/block.yaml
  locale/en/corteza-webapp-compose/field.yaml
  locale/en/corteza-webapp-reporter/display-element.yaml
Labels: enhancement, frontend

#1221 Fix max-height issue for ItemPicker in safari
  client/web/compose/src/components/Admin/Module/DiscoverySettings.vue
  client/web/compose/src/components/Admin/Module/Records/ColumnPicker.vue
  client/web/compose/src/components/Admin/Module/Validation.vue
  client/web/compose/src/components/PageBlocks/RecordConfigurator.vue
  client/web/compose/src/components/PageBlocks/RecordListConfigurator.vue
  client/web/compose/src/components/Public/Record/Exporter/Configurator.vue
Labels: bug, frontend

#1196 Resolve blocks being hidden forever
  client/web/compose/src/components/PageBlocks/TabsBase.vue
  client/web/compose/src/views/Admin/Pages/Builder.vue
Labels: frontend
